### ISSUE TITLE
Weird ZIP Codes in Sample Database

### ISSUE THREAD

**Issue by sfaria27** [mytiki/platform-cap-bulk#13]
Zip codes look to be in the sample lake as sha256 hashes. This may be correct or not. Requires investigation into the source data.

**Comment by sfaria27** [comment]
![Image](https://github.com/tiki/ocean/assets/81697281/9e2c3464-ab7b-47bf-80e0-7ab584d3f593)

**Comment by mike-audi** [comment]
Checked out the raw input data, zip codes are in-fact prehashed by the customer, so the records in the lake are in-fact correct.
